package codegen

import (
	"regexp"
	"strings"
	"testing"

	"github.com/flagifyhq/cli/internal/api"
)

func TestMain(m *testing.M) {
	nowStamp = func() string { return "2026-04-19T00:00:00Z" }
	m.Run()
}

func flagsFromKeys(keys ...string) []api.Flag {
	out := make([]api.Flag, 0, len(keys))
	for _, k := range keys {
		out = append(out, api.Flag{Key: k})
	}
	return out
}

func TestKebabToPascal(t *testing.T) {
	cases := map[string]string{
		"new-checkout-flow":  "NewCheckoutFlow",
		"dark-mode":          "DarkMode",
		"onboarding-v2":      "OnboardingV2",
		"enable-ai-features": "EnableAiFeatures",
		"x":                  "X",
		"":                   "",
		"a-b":                "AB",
	}
	for in, want := range cases {
		if got := kebabToPascal(in); got != want {
			t.Errorf("kebabToPascal(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestGenerateTypeScript_SortsAlphabetically(t *testing.T) {
	out := GenerateTypeScript(flagsFromKeys("zeta", "alpha", "mike"), "Web App")

	if !strings.Contains(out, "// Project: Web App") {
		t.Fatalf("missing project header:\n%s", out)
	}
	if !strings.Contains(out, "// Generated: 2026-04-19T00:00:00Z") {
		t.Fatalf("missing generated stamp:\n%s", out)
	}
	aIdx := strings.Index(out, `"alpha"`)
	mIdx := strings.Index(out, `"mike"`)
	zIdx := strings.Index(out, `"zeta"`)
	if !(aIdx < mIdx && mIdx < zIdx) {
		t.Errorf("keys not sorted alphabetically: a=%d m=%d z=%d", aIdx, mIdx, zIdx)
	}
	if !strings.Contains(out, "export type FlagKey = keyof typeof FLAG_KEYS;") {
		t.Errorf("missing FlagKey type:\n%s", out)
	}
}

func TestGenerateTypeScript_Empty(t *testing.T) {
	out := GenerateTypeScript(nil, "Empty Project")
	if !strings.Contains(out, "export const FLAG_KEYS = {} as const;") {
		t.Errorf("expected empty object, got:\n%s", out)
	}
	if !strings.Contains(out, "export type FlagKey = keyof typeof FLAG_KEYS;") {
		t.Errorf("missing type declaration:\n%s", out)
	}
}

func TestGenerateTypeScript_Deduplicates(t *testing.T) {
	out := GenerateTypeScript(flagsFromKeys("foo", "foo", "bar"), "Dedup")
	if strings.Count(out, `"foo": "foo"`) != 1 {
		t.Errorf("expected single foo entry, got:\n%s", out)
	}
}

func TestGenerateGo_BasicShape(t *testing.T) {
	out, err := GenerateGo(flagsFromKeys("new-checkout-flow", "dark-mode"), "Web App", "flagify")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	for _, want := range []string{
		"// Auto-generated by Flagify CLI — do not edit manually",
		"// Project: Web App",
		"package flagify",
		`FlagDarkMode`,
		`= "dark-mode"`,
		`FlagNewCheckoutFlow = "new-checkout-flow"`,
		"const (",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("missing %q in output:\n%s", want, out)
		}
	}

	// Sorted by key (= by identifier since Flag prefix is constant).
	darkIdx := strings.Index(out, "FlagDarkMode")
	newIdx := strings.Index(out, "FlagNewCheckoutFlow")
	if darkIdx > newIdx {
		t.Errorf("Go consts not alphabetical: dark=%d new=%d", darkIdx, newIdx)
	}
}

func TestGenerateGo_DefaultPackage(t *testing.T) {
	out, err := GenerateGo(flagsFromKeys("x"), "Any", "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "package flagify") {
		t.Errorf("expected default package flagify, got:\n%s", out)
	}
}

func TestGenerateGo_InvalidPackage(t *testing.T) {
	_, err := GenerateGo(flagsFromKeys("x"), "Any", "123bad")
	if err == nil {
		t.Fatal("expected error for invalid Go package name")
	}
}

func TestGenerateGo_Empty(t *testing.T) {
	out, err := GenerateGo(nil, "Empty", "flagify")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "// no flags defined yet") {
		t.Errorf("missing empty comment:\n%s", out)
	}
	if strings.Contains(out, "const (") {
		t.Errorf("empty output should not emit const block:\n%s", out)
	}
	if !strings.Contains(out, "package flagify") {
		t.Errorf("missing package declaration:\n%s", out)
	}
}

func TestGenerateGo_SkipsInvalidKeys(t *testing.T) {
	// "Bad Key" is not kebab-case — it should be skipped from the generated
	// Go output. We verify via the emitted const block.
	flags := flagsFromKeys("good-key", "Bad Key")
	out, err := GenerateGo(flags, "Mixed", "flagify")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "FlagGoodKey") {
		t.Errorf("expected valid key to appear:\n%s", out)
	}
	if strings.Contains(out, "Bad Key") {
		t.Errorf("invalid key should be skipped:\n%s", out)
	}
}

func TestGenerateGo_DetectsCollision(t *testing.T) {
	// Valid kebab keys (lowercase only) never collide under kebabToPascal, so
	// we cannot exercise the duplicate-identifier error path with real input.
	// To cover the defensive branch we relax the regex to also accept
	// uppercase, then feed two keys that normalise to the same identifier:
	// "foo-bar" → "FlagFooBar" and "Foo-bar" → "FlagFooBar".
	orig := kebabKeyRe
	kebabKeyRe = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9]*(-[A-Za-z0-9]+)*$`)
	t.Cleanup(func() { kebabKeyRe = orig })

	_, err := GenerateGo(flagsFromKeys("foo-bar", "Foo-bar"), "Collide", "flagify")
	if err == nil {
		t.Fatal("expected duplicate-identifier error, got nil")
	}
	if !strings.Contains(err.Error(), "duplicate Go identifier") {
		t.Errorf("expected duplicate-identifier error, got: %v", err)
	}
	if !strings.Contains(err.Error(), "FlagFooBar") {
		t.Errorf("expected offending identifier in error, got: %v", err)
	}
}

func TestGenerateTypeScript_SanitizesProjectName(t *testing.T) {
	malicious := "Web App\npackage evil\nvar X = 1"
	out := GenerateTypeScript(flagsFromKeys("k"), malicious)
	if strings.Contains(out, "\npackage evil") {
		t.Errorf("newline in project name broke out of comment:\n%s", out)
	}
	if !strings.Contains(out, "// Project: Web App package evil var X = 1") {
		t.Errorf("expected newlines collapsed to spaces:\n%s", out)
	}
}

func TestGenerateGo_SanitizesProjectName(t *testing.T) {
	malicious := "Web App\npackage evil"
	out, err := GenerateGo(flagsFromKeys("k"), malicious, "flagify")
	if err != nil {
		t.Fatalf("GenerateGo: %v", err)
	}
	if strings.Contains(out, "\npackage evil") {
		t.Errorf("newline in project name broke out of comment:\n%s", out)
	}
	// The actual package declaration must still be the caller-supplied one.
	if strings.Count(out, "\npackage ") != 1 {
		t.Errorf("expected exactly one package declaration:\n%s", out)
	}
}

func TestInvalidKeys(t *testing.T) {
	bad := InvalidKeys(flagsFromKeys("good", "Not Kebab", "also-good", "With_Underscore"))
	if len(bad) != 2 {
		t.Fatalf("expected 2 invalid keys, got %v", bad)
	}
	if bad[0] != "Not Kebab" || bad[1] != "With_Underscore" {
		t.Errorf("unexpected order: %v", bad)
	}
}
