// Package codegen generates source files with flag keys exported as typed
// constants. Used by the `flagify types` command to give applications compile-
// time checks on flag identifiers.
package codegen

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/flagifyhq/cli/internal/api"
)

var (
	kebabKeyRe     = regexp.MustCompile(`^[a-z][a-z0-9]*(-[a-z0-9]+)*$`)
	goIdentifierRe = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)
)

// kebabToPascal converts "new-checkout-flow" → "NewCheckoutFlow".
// Empty segments and non-alphanumeric input yield an empty string.
func kebabToPascal(key string) string {
	if key == "" {
		return ""
	}
	parts := strings.Split(key, "-")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		if len(p) > 1 {
			b.WriteString(p[1:])
		}
	}
	return b.String()
}

// sanitizeComment collapses newlines and carriage returns in free-text fields
// (project names come from user input in the dashboard) so they cannot break
// out of the leading "// …" comments in the generated file.
func sanitizeComment(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "\r", " "), "\n", " ")
}

// sortedKeys returns the flag keys in alphabetical order for stable output.
func sortedKeys(flags []api.Flag) []string {
	keys := make([]string, 0, len(flags))
	seen := make(map[string]struct{}, len(flags))
	for _, f := range flags {
		if _, dup := seen[f.Key]; dup {
			continue
		}
		seen[f.Key] = struct{}{}
		keys = append(keys, f.Key)
	}
	sort.Strings(keys)
	return keys
}

// nowStamp returns the current UTC timestamp in RFC3339. Overridable in tests.
var nowStamp = func() string { return time.Now().UTC().Format(time.RFC3339) }

// GenerateTypeScript returns a TypeScript source file exporting FLAG_KEYS and
// a FlagKey union type.
func GenerateTypeScript(flags []api.Flag, projectName string) string {
	keys := sortedKeys(flags)

	var b strings.Builder
	b.WriteString("// Auto-generated by Flagify CLI — do not edit manually\n")
	fmt.Fprintf(&b, "// Project: %s\n", sanitizeComment(projectName))
	fmt.Fprintf(&b, "// Generated: %s\n\n", nowStamp())

	if len(keys) == 0 {
		b.WriteString("export const FLAG_KEYS = {} as const;\n\n")
		b.WriteString("export type FlagKey = keyof typeof FLAG_KEYS;\n")
		return b.String()
	}

	b.WriteString("export const FLAG_KEYS = {\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "  %q: %q,\n", k, k)
	}
	b.WriteString("} as const;\n\n")
	b.WriteString("export type FlagKey = keyof typeof FLAG_KEYS;\n")
	return b.String()
}

// GenerateGo returns a Go source file exporting typed constants for each flag
// key. Returns an error when two kebab keys collide into the same Go
// identifier (which would produce uncompilable code).
func GenerateGo(flags []api.Flag, projectName, packageName string) (string, error) {
	if packageName == "" {
		packageName = "flagify"
	}
	if !goIdentifierRe.MatchString(packageName) {
		return "", fmt.Errorf("invalid Go package name: %q", packageName)
	}

	keys := sortedKeys(flags)

	type entry struct {
		ident string
		key   string
	}
	var entries []entry
	collisions := map[string][]string{}

	for _, k := range keys {
		if !kebabKeyRe.MatchString(k) {
			continue
		}
		ident := "Flag" + kebabToPascal(k)
		collisions[ident] = append(collisions[ident], k)
		entries = append(entries, entry{ident: ident, key: k})
	}

	for ident, sources := range collisions {
		if len(sources) > 1 {
			return "", fmt.Errorf("duplicate Go identifier %q from keys %v", ident, sources)
		}
	}

	var b strings.Builder
	b.WriteString("// Auto-generated by Flagify CLI — do not edit manually\n")
	fmt.Fprintf(&b, "// Project: %s\n", sanitizeComment(projectName))
	fmt.Fprintf(&b, "// Generated: %s\n\n", nowStamp())
	fmt.Fprintf(&b, "package %s\n\n", packageName)

	if len(entries) == 0 {
		b.WriteString("// no flags defined yet\n")
		return b.String(), nil
	}

	// Pad idents for column alignment.
	maxIdent := 0
	for _, e := range entries {
		if len(e.ident) > maxIdent {
			maxIdent = len(e.ident)
		}
	}

	b.WriteString("const (\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "\t%-*s = %q\n", maxIdent, e.ident, e.key)
	}
	b.WriteString(")\n")

	return b.String(), nil
}

// InvalidKeys returns the subset of flag keys that cannot be converted into a
// Go identifier. The command layer prints these as warnings.
func InvalidKeys(flags []api.Flag) []string {
	var bad []string
	for _, f := range flags {
		if !kebabKeyRe.MatchString(f.Key) {
			bad = append(bad, f.Key)
		}
	}
	sort.Strings(bad)
	return bad
}
