package cmd

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func typesFakeServer(t *testing.T) *httptest.Server {
	t.Helper()
	return httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.Method == "GET" && r.URL.Path == "/v1/projects/proj_01/flags":
			w.Header().Set("Content-Type", "application/json")
			_ = json.NewEncoder(w).Encode([]map[string]any{
				{"id": "f1", "key": "new-checkout-flow", "name": "Checkout", "type": "boolean"},
				{"id": "f2", "key": "dark-mode", "name": "Dark Mode", "type": "boolean"},
			})
		case r.Method == "GET" && r.URL.Path == "/v1/projects/proj_01":
			w.Header().Set("Content-Type", "application/json")
			_ = json.NewEncoder(w).Encode(map[string]any{
				"id":   "proj_01",
				"name": "Web App",
				"slug": "web-app",
			})
		default:
			t.Fatalf("unexpected request: %s %s", r.Method, r.URL.Path)
		}
	}))
}

func resetTypesFlags(t *testing.T) {
	t.Helper()
	t.Cleanup(func() {
		for _, name := range []string{"typescript", "go", "output", "package"} {
			f := typesCmd.Flags().Lookup(name)
			if f == nil {
				continue
			}
			_ = f.Value.Set(f.DefValue)
			f.Changed = false
		}
	})
}

func TestTypes_RequiresLanguageFlag(t *testing.T) {
	writeTestConfig(t, "http://127.0.0.1:0")
	resetTypesFlags(t)

	_, err := runRoot(t, "types", "-p", "proj_01")
	if err == nil {
		t.Fatal("expected error when no language flag provided")
	}
	if !strings.Contains(err.Error(), "--typescript") || !strings.Contains(err.Error(), "--go") {
		t.Fatalf("error should mention both flags, got: %v", err)
	}
}

func TestTypes_MutuallyExclusive(t *testing.T) {
	writeTestConfig(t, "http://127.0.0.1:0")
	resetTypesFlags(t)

	_, err := runRoot(t, "types", "--typescript", "--go", "-p", "proj_01")
	if err == nil {
		t.Fatal("expected error when both --typescript and --go passed")
	}
}

func TestTypes_TypeScript_HappyPath(t *testing.T) {
	srv := typesFakeServer(t)
	defer srv.Close()
	writeTestConfig(t, srv.URL)
	resetTypesFlags(t)

	outFile := filepath.Join(t.TempDir(), "flags.ts")
	if _, err := runRoot(t, "types", "--typescript", "-o", outFile, "-p", "proj_01"); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	data, err := os.ReadFile(outFile)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	got := string(data)

	for _, want := range []string{
		"// Auto-generated by Flagify CLI",
		"// Project: Web App",
		"export const FLAG_KEYS",
		`"dark-mode": "dark-mode"`,
		`"new-checkout-flow": "new-checkout-flow"`,
		"export type FlagKey = keyof typeof FLAG_KEYS;",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in output:\n%s", want, got)
		}
	}
	// Alphabetical: dark-mode before new-checkout-flow.
	if strings.Index(got, "dark-mode") > strings.Index(got, "new-checkout-flow") {
		t.Errorf("keys not alphabetically sorted:\n%s", got)
	}
}

func TestTypes_Go_HappyPath(t *testing.T) {
	srv := typesFakeServer(t)
	defer srv.Close()
	writeTestConfig(t, srv.URL)
	resetTypesFlags(t)

	outFile := filepath.Join(t.TempDir(), "flags.go")
	if _, err := runRoot(t, "types", "--go", "--package", "myflags", "-o", outFile, "-p", "proj_01"); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	data, err := os.ReadFile(outFile)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	got := string(data)

	for _, want := range []string{
		"// Auto-generated by Flagify CLI",
		"// Project: Web App",
		"package myflags",
		"FlagDarkMode",
		`= "dark-mode"`,
		"FlagNewCheckoutFlow",
		`= "new-checkout-flow"`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in output:\n%s", want, got)
		}
	}
}

func TestTypes_EmptyFlagList(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		switch r.URL.Path {
		case "/v1/projects/proj_01/flags":
			_ = json.NewEncoder(w).Encode([]map[string]any{})
		case "/v1/projects/proj_01":
			_ = json.NewEncoder(w).Encode(map[string]any{"id": "proj_01", "name": "Empty", "slug": "empty"})
		default:
			t.Fatalf("unexpected request: %s %s", r.Method, r.URL.Path)
		}
	}))
	defer srv.Close()
	writeTestConfig(t, srv.URL)
	resetTypesFlags(t)

	outFile := filepath.Join(t.TempDir(), "flags.ts")
	stdout, _, err := runRootCapture(t, "types", "--typescript", "-o", outFile, "-p", "proj_01")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	data, _ := os.ReadFile(outFile)
	got := string(data)
	if !strings.Contains(got, "export const FLAG_KEYS = {} as const;") {
		t.Errorf("expected empty object literal:\n%s", got)
	}
	if !strings.Contains(stdout, "(0 flags)") {
		t.Errorf("expected 0-flags success line, got: %s", stdout)
	}
}

func TestTypes_Go_SkippedKeysWarning(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		switch r.URL.Path {
		case "/v1/projects/proj_01/flags":
			_ = json.NewEncoder(w).Encode([]map[string]any{
				{"id": "f1", "key": "dark-mode", "name": "Dark", "type": "boolean"},
				{"id": "f2", "key": "Bad Key", "name": "Legacy", "type": "boolean"},
			})
		case "/v1/projects/proj_01":
			_ = json.NewEncoder(w).Encode(map[string]any{"id": "proj_01", "name": "Mixed", "slug": "mixed"})
		default:
			t.Fatalf("unexpected request: %s %s", r.Method, r.URL.Path)
		}
	}))
	defer srv.Close()
	writeTestConfig(t, srv.URL)
	resetTypesFlags(t)

	outFile := filepath.Join(t.TempDir(), "flags.go")
	_, stderr, err := runRootCapture(t, "types", "--go", "-o", outFile, "-p", "proj_01")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(stderr, "skipped 1 key") {
		t.Errorf("expected skip warning on stderr, got: %q", stderr)
	}
	if !strings.Contains(stderr, "Bad Key") {
		t.Errorf("expected offending key in warning, got: %q", stderr)
	}
}

func TestTypes_ProjectFallbackFromConfig(t *testing.T) {
	srv := typesFakeServer(t)
	defer srv.Close()

	home := t.TempDir()
	t.Setenv("HOME", home)
	cfgDir := filepath.Join(home, ".flagify")
	if err := os.MkdirAll(cfgDir, 0o700); err != nil {
		t.Fatalf("mkdir config dir: %v", err)
	}
	cfg := map[string]any{
		"accessToken": "test-token",
		"apiUrl":      srv.URL,
		"projectId":   "proj_01",
	}
	data, _ := json.Marshal(cfg)
	if err := os.WriteFile(filepath.Join(cfgDir, "config.json"), data, 0o600); err != nil {
		t.Fatalf("write config: %v", err)
	}
	resetTypesFlags(t)

	outFile := filepath.Join(t.TempDir(), "flags.ts")
	if _, err := runRoot(t, "types", "--typescript", "-o", outFile); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	data, err := os.ReadFile(outFile)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	if !strings.Contains(string(data), "new-checkout-flow") {
		t.Errorf("expected flags from proj_01, got:\n%s", data)
	}
}

func TestTypes_OverwriteUnknownFileRequiresConfirm(t *testing.T) {
	srv := typesFakeServer(t)
	defer srv.Close()
	writeTestConfig(t, srv.URL)
	resetTypesFlags(t)

	outFile := filepath.Join(t.TempDir(), "flags.ts")
	if err := os.WriteFile(outFile, []byte("// hand-authored, do not clobber\nexport const foo = 1\n"), 0o600); err != nil {
		t.Fatalf("seed file: %v", err)
	}

	// In a non-TTY test context, ui.Confirm returns true (skip=true path via
	// terminal check), so the write proceeds. This test documents that
	// contract: non-TTY callers get silent overwrites, and the regression we
	// guard against is human users losing hand-authored files at a prompt.
	if _, err := runRoot(t, "types", "--typescript", "-o", outFile, "-p", "proj_01"); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	data, _ := os.ReadFile(outFile)
	if !strings.Contains(string(data), "Auto-generated by Flagify CLI") {
		t.Errorf("expected file to be overwritten with generated content:\n%s", data)
	}
}

func TestTypes_OverwriteFlagifyHeaderedFileSilently(t *testing.T) {
	srv := typesFakeServer(t)
	defer srv.Close()
	writeTestConfig(t, srv.URL)
	resetTypesFlags(t)

	outFile := filepath.Join(t.TempDir(), "flags.ts")
	if err := os.WriteFile(outFile, []byte("// Auto-generated by Flagify CLI — do not edit manually\n// old content\n"), 0o600); err != nil {
		t.Fatalf("seed file: %v", err)
	}
	if _, err := runRoot(t, "types", "--typescript", "-o", outFile, "-p", "proj_01"); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	data, _ := os.ReadFile(outFile)
	if !strings.Contains(string(data), "new-checkout-flow") {
		t.Errorf("expected regenerated content with flag keys:\n%s", data)
	}
}

func TestTypes_DefaultOutputName(t *testing.T) {
	srv := typesFakeServer(t)
	defer srv.Close()
	writeTestConfig(t, srv.URL)
	resetTypesFlags(t)

	// Run in a temp dir so the default output lands there.
	tmp := t.TempDir()
	orig, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	if err := os.Chdir(tmp); err != nil {
		t.Fatalf("chdir: %v", err)
	}
	t.Cleanup(func() { _ = os.Chdir(orig) })

	if _, err := runRoot(t, "types", "--typescript", "-p", "proj_01"); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if _, err := os.Stat(filepath.Join(tmp, "flagify.ts")); err != nil {
		t.Fatalf("default file not created: %v", err)
	}
}
