package cmd

import (
	"bytes"
	"fmt"
	"os"
	"strings"

	"github.com/flagifyhq/cli/internal/codegen"
	"github.com/flagifyhq/cli/internal/config"
	"github.com/flagifyhq/cli/internal/ui"
	"github.com/spf13/cobra"
)

// flagifyHeader marks files emitted by `flagify types`. When the destination
// already exists and starts with this marker we overwrite without asking; any
// other existing file is treated as user-authored and requires confirmation.
var flagifyHeader = []byte("// Auto-generated by Flagify CLI")

var typesCmd = &cobra.Command{
	Use:   "types",
	Short: "Generate typed flag key constants for your codebase",
	Long: `Generate a source file exporting all flag keys in the current project
as typed constants. Use the output in your application code for compile-time
checks on flag identifiers.

Exactly one of --typescript or --go must be provided.`,
	Example: `  flagify types --typescript                 # writes ./flagify.ts
  flagify types --go                         # writes ./flagify.go
  flagify types --typescript -o src/flags.ts # custom output path
  flagify types --go --package myflags       # custom Go package name`,
	RunE: func(cmd *cobra.Command, args []string) error {
		tsOut, _ := cmd.Flags().GetBool("typescript")
		goOut, _ := cmd.Flags().GetBool("go")
		output, _ := cmd.Flags().GetString("output")
		pkgName, _ := cmd.Flags().GetString("package")

		if tsOut == goOut { // both true or both false
			return fmt.Errorf("exactly one of --typescript or --go is required")
		}

		cfg, err := config.Load()
		if err != nil {
			return err
		}
		projectID := resolveFlag(cmd, "project", cfg.ProjectID)
		if projectID == "" {
			return fmt.Errorf("--project is required (or run 'flagify projects pick')")
		}

		client, err := getClient()
		if err != nil {
			return err
		}

		flags, err := client.ListFlags(projectID)
		if err != nil {
			return handleAccessError(err)
		}

		project, err := client.GetProject(projectID)
		if err != nil {
			return handleAccessError(err)
		}

		var (
			contents string
			ext      string
		)
		if tsOut {
			contents = codegen.GenerateTypeScript(flags, project.Name)
			ext = "ts"
		} else {
			contents, err = codegen.GenerateGo(flags, project.Name, pkgName)
			if err != nil {
				return err
			}
			ext = "go"
		}

		if output == "" {
			output = "flagify." + ext
		}

		if err := confirmOverwrite(cmd, output); err != nil {
			return err
		}

		if skipped := codegen.InvalidKeys(flags); len(skipped) > 0 && goOut {
			fmt.Fprintln(os.Stderr, ui.Warning(fmt.Sprintf(
				"skipped %d key(s) that are not valid Go identifiers: %s",
				len(skipped), strings.Join(skipped, ", "),
			)))
		}

		if err := os.WriteFile(output, []byte(contents), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", output, err)
		}

		flagWord := "flags"
		if len(flags) == 1 {
			flagWord = "flag"
		}
		fmt.Println(ui.Success(fmt.Sprintf("Generated %s (%d %s)", output, len(flags), flagWord)))
		return nil
	},
}

// confirmOverwrite prompts the user before clobbering a destination that was
// not produced by a previous `flagify types` run. Non-existent targets and
// files whose first bytes carry the Flagify auto-generated header are written
// without prompting, matching the decision-log stance that regeneration is a
// routine operation.
func confirmOverwrite(cmd *cobra.Command, path string) error {
	existing, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("inspect %s: %w", path, err)
	}
	if bytes.HasPrefix(existing, flagifyHeader) {
		return nil
	}
	yes, _ := cmd.Flags().GetBool("yes")
	confirmed, err := ui.Confirm(fmt.Sprintf("%s exists and was not generated by Flagify. Overwrite?", path), yes)
	if err != nil {
		return err
	}
	if !confirmed {
		return fmt.Errorf("aborted: %s not overwritten", path)
	}
	return nil
}

func init() {
	typesCmd.Flags().BoolP("typescript", "t", false, "Generate TypeScript output")
	typesCmd.Flags().BoolP("go", "g", false, "Generate Go output")
	typesCmd.Flags().StringP("output", "o", "", "Output file path (default: flagify.<ext> in cwd)")
	typesCmd.Flags().String("package", "flagify", "Go package name (only with --go)")
	typesCmd.MarkFlagsMutuallyExclusive("typescript", "go")

	rootCmd.AddCommand(typesCmd)
}
